### ISSUE TITLE
The performance of loading case search is kind of slow, it takes 8 seconds to load 5000 records on particular hardware

### ISSUE THREAD

**Issue by radiateboy** [kiwitcms/Kiwi#1173] opened 2019-10-12 03:45 UTC

**Comment by atodorov** [comment] 2019-10-13 08:36
We need more information than that. On public.tenant it takes around 5-6 seconds to load the same page with around 5k results on a t2.small AWS instance. 

What is your hardware setup/system parameters ? What is your DB, where is it hosted and how is it setup performance wise ?
Can you measure which part exactly is the slowest for you (e.g. web page load time, DB select, data transfer, etc) ?

**Comment by radiateboy** [comment] 2019-10-14 07:18
My environment is Huawei Cloud PaaS.

**Comment by radiateboy** [comment] 2019-10-14 09:50
my tcms  setup parameters 
![image](https://user-images.githubusercontent.com/9248754/66742493-55a15c00-eeaa-11e9-98ae-958f030de372.png)
my database setup parameters 
![image](https://user-images.githubusercontent.com/9248754/66742610-a0bb6f00-eeaa-11e9-9b11-03f56ffb484b.png)
and i request Seache Case menu connect info
![image](https://user-images.githubusercontent.com/9248754/66742795-0f98c800-eeab-11e9-859a-fffee26ee355.png)

**Comment by radiateboy** [comment] 2019-10-14 09:51
i used mariadb:10.3.1

**Comment by atodorov** [comment] 2019-10-17 12:46
From the pictures you posted it is evident that it actually takes only 8 seconds to load the test cases themselves, not 15 like you wrote. 

The demo uses a t2.small instance (https://aws.amazon.com/ec2/instance-types/) which is totally unoptimized, the DB runs inside a container and the containers are backed by files on the filesystem, not on block storage and there the same API call takes 2 seconds. 
The subsequent RPC calls take on average 150ms each.

^^^ that is `docker-compose up` on a default instance from AWS without doing anything else. Is this what you did ? 

You don't say anything about your I/O setup or parameters, nor anything about network connection between DB and app server, network speed between App and Browser. 

**There's no way to judge performance in different environments when we don't have all the details available.**

I lean towards your disk/DB just being slow. Way slower than what we get from Amazon. 

We can update documentation and probably think about finding some sort of benchmark suite so we can compare various environments more easily, we could probably spend some time listing quick tips for optimization (you need to know what you are doing there). However there's no way to know how different hosting environments work and perform.

**Comment by atodorov** [comment] 2020-08-20 09:39
Essentially duplicate of https://github.com/kiwitcms/Kiwi/issues/1014 but would benefit from some documentation.

**Closed** 2021-03-26 22:47 UTC
