### ISSUE TITLE
Cannot include testcases from another testplan

### ISSUE THREAD

**Issue by fahdilahady** [kiwitcms/Kiwi#2193] opened 2021-01-11 07:45 UTC
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
1. There is no filter based on testplan
2. select button doesnt have any action

### Steps to Reproduce

1. login
2. search for test plan you want to append the test cases
3. select the test plan
4. on the search icon (next to add test case button)
5. just let any filter search
6. check one or multiple test case
7. click select button
8. return to testplan window but the selected testcases does NOT append

https://user-images.githubusercontent.com/42434078/104155447-d0448880-5419-11eb-826a-4b5bf09e5411.mov

### Expected results
possibility to append test cases from another test plan.

**Comment by atodorov** [comment] 2021-01-11 08:38
Duplicate of #2100

**Closed by atodorov** 2021-01-11 08:38 UTC
