### ISSUE TITLE
cannot batch add case into testplan with click advanced search button

### ISSUE THREAD

**Issue by hanyce** [kiwitcms/Kiwi#2305] opened 2021-03-16 02:37 UTC
### Description of problem
in chrome version 88,  they just recently disallowed synchronous ajax during end-of-page events (like beforeunload and unload)
![image](https://user-images.githubusercontent.com/37854396/111247764-907d6580-8643-11eb-8c97-3e99c0018b01.png)

here is the details:
https://www.chromestatus.com/feature/4664843055398912
https://stackoverflow.com/questions/55676319/ajax-synchronous-request-failing-in-chrome

**Comment by hanyce** [comment] 2021-03-16 02:56
I already have a way to solve this problem.
open chrome://flags/ to set Allows synchronous XHR requests in page dismissal to enable.

but can you Optimize the code to avoid this problem？

**Comment by atodorov** [comment] 2021-03-16 06:38
Duplicate of #2100

**Closed by atodorov** 2021-03-16 06:38 UTC

**Comment by hanyce** [comment] 2021-03-16 06:42
@atodorov will you fix this problem in codes near future？
