### ISSUE TITLE
RPC selectors not returning values for certain fields

### ISSUE THREAD

**Issue by bensialih** [kiwitcms/Kiwi#2467] opened 2021-07-25 13:32 UTC
There seems to be an issue with Kiwi using grappelli on certain pages.

### Description of problem
Grappelli cant be used on pages like
- new testplan
- new testcase
- new bug

This seems to be where the bug is focused as I think grappelli is being used on the rich text form

### Version or commit hash
latest at the time of error
hash: **c3f864dbea2a3ed7578ec342f6f2aea2eb504df2** 

### Steps to Reproduce

1. clone the Kiwi repo
2. **npm install --save** inside tcms folder
3. **run migration** on root folder
4. manage.py collectstatic
5. runserver
6. login
7. navigate to /plan/new/ and load
8. check the error console for error 

### Actual results
1. The layout is not good.
This may be because of grappelli failing to load please see screenshots

![Screenshot from 2021-07-25 14-23-21](https://user-images.githubusercontent.com/14818716/126900870-c75337cc-d0ab-4f7f-bbd1-72e828b417ca.png)
![Screenshot from 2021-07-25 11-01-08](https://user-images.githubusercontent.com/14818716/126900871-23e7530a-5bcb-4183-a9e1-4481d2ebcf24.png)

2. Grappelli as a file is loading just fine but actually using grappelli as a library doesnt seem to work.
3. The loading of the page seems to just cycle without any finality.
again this may be because Grappelli is missing

### Expected results

Expected the usual Grappelli awesomeness.

### Additional info 
- installed nvm install **6.14.4** and **10.10.0**
- python3.7
- no errors on backend and seems fine

**Comment by arnauvp** [comment] 2021-08-05 11:23
We see this error too. Additionally, our test plans don't seem to load on 10.2 when creating a new test run (so we can't use Kiwi 😢). This used to work on 10.1. 

<img width="551" alt="Screenshot 2021-08-05 at 13 19 24" src="https://user-images.githubusercontent.com/1090103/128341661-1be8885a-eb83-48b5-afd5-354aa622f3c1.png">

Could it be due to the missing library, as it handles "related lookups"?

**Comment by arnauvp** [comment] 2021-08-05 11:33
BTW the problem above is also visible at your [public instance](https://public.tenant.kiwitcms.org/runs/new/).

<img width="1548" alt="Screenshot 2021-08-05 at 13 31 29" src="https://user-images.githubusercontent.com/1090103/128343026-92f695e8-f241-4471-b700-94e17076df6d.png">

These queries return empty arrays for Test Plans:
<img width="783" alt="Screenshot 2021-08-05 at 13 31 46" src="https://user-images.githubusercontent.com/1090103/128343057-8f45f038-878f-42d6-b4a9-bec4879c7f5e.png">

Can you please raise the priority of this issue and release a new version with the fix?
Thanks

**Comment by atodorov** [comment] 2021-08-05 12:53
The grappelli warning is not related.  The root cause seems to be that some of the functions loading information into these drop down widgets have been modified to expect a list of values as part of the multi-select changes for telemetry pages. However on pages like search or mutable the product field supports single select only. For example `updateTestPlanSelectFromProduct` will use the `product__in: "1234"` lookup which will not return any values. It needs to be `product_in: [1234]`

@asankov can you take a look at this. See `git log -- static/js/utils.js`, everything since 1fa95b71895ef8c175ba71cc6a568d13633635da

**Comment by asankov** [comment] 2021-08-05 16:49
@atodorov the culprit seems to be exactly 1fa95b7 that changes:
```diff
-        jsonRPC('TestPlan.filter', {product: productId}, updateCallback);
+        jsonRPC('TestPlan.filter', {product__in: productIds}, updateCallback);
```

**Comment by arnauvp** [comment] 2021-08-10 10:28
@asankov @atodorov any chance to get the fix merged and a new release on Docker hub? Or is there a workaround for entering a test run? It seems to me this bug blocks the main functionality of the tool…

**Closed** 2021-08-11 07:49 UTC

**Comment by arnauvp** [comment] 2021-08-11 12:04
Thanks, the fix for the selectors works! 🥳 

But FYI the original problem about grappelli is still there:

`Uncaught ReferenceError: grappelli is not defined`

**Comment by bensialih** [comment] 2021-08-12 15:48
@arnauvp I have found the solution to the missing grappelli.
The docs for using grappelli show that there is a var that should be set before use.

```
<script type="text/javascript" charset="utf-8">
    // GLOBALS
    var grappelli = {},
        ADMIN_URL = "/admin/",
        MODEL_URL_ARRAY = [],
        DATE_FORMAT = "%Y-%m-%d",
        TIME_FORMAT = "%H:%M:%S",
        DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S";
</script>
``` 

The above can be found in the django-grappelli templates when they are used.
