### ISSUE TITLE
documentation - steps for docker installation incomplete

### ISSUE THREAD

**Issue by realkot** [kiwitcms/Kiwi#345] opened 2018-05-14 12:27 UTC
### Description of problem
documentation - steps for docker installation incomplete

### Component (web, API, etc)
web

### Steps to Reproduce

1. follow instructions on http://kiwitcms.readthedocs.io/en/latest/installing_docker.html
2. You can start using Kiwi TCMS by executing:
`docker-compose up -d`

### Actual results
```
root@kiwi:~# docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

### Expected results
following the docs instructions - we get working kiwi TCMS

### Additional info
After running this command i get
```
root@kiwi:~# docker run kiwitcms/kiwi
AH00526: Syntax error on line 34 of /etc/httpd/conf.d/kiwi-httpd.conf:
SSLCertificateFile: file '/etc/kiwitcms/ssl/localhost.crt' does not exist or is empty
```

**Comment by atodorov** [comment] 2018-05-16 06:53
Duplicate of #344

**Closed by atodorov** 2018-05-16 06:53 UTC
