### ISSUE TITLE
[Testcases] Search page show duplication records in component dropdown

### ISSUE THREAD

**Issue by shiron-truong** [kiwitcms/Kiwi#2342] opened 2021-04-15 01:25 UTC
### Description of problem
![2021-04-15_08-19-41 (1)](https://user-images.githubusercontent.com/50346670/114800390-d3a63200-9dc3-11eb-901b-9614fa2c710e.gif)

![image](https://user-images.githubusercontent.com/50346670/114799885-e0765600-9dc2-11eb-82b2-a77d8cf6e20c.png)

### Version or commit hash (if applicable)
Kiwi: 10.0

### Steps to Reproduce

1. Open Testcases item from menu.
2. Select product
3. click Component dropdown list

### Actual results
Show duplication value of component.

### Expected results
Show distinct value of component.

**Comment by atodorov** [comment] 2021-04-22 13:01
To reproduce we need a component which is attached to more than 1 cases. The RPC includes the underlying `cases` field into the response which is a one-to-many relationship. This needs to be filtered out on the UI.

**Comment by atodorov** [comment] 2021-07-01 16:24
This has been fixed in 9788ef05db42a73b5fa3b68c289fb3a9797ea92c, which was deployed as v10.1 after this bug has been opened but the commit log doesn't reference this issue.

Can't reproduce on https://public.tenant.kiwitcms.org so closing.

**Closed by atodorov** 2021-07-01 16:24 UTC
Labels: bug
