### ISSUE TITLE
Cannot open GitHub issues through report bug link

### ISSUE THREAD

**Issue by mattouille** [kiwitcms/Kiwi#530] opened 2018-09-21 19:34 UTC
### Description of problem

After setting up a issue tracker integration for GitHub I am unable to open a bug on GitHub.

### Version or commit hash (if applicable)

5.3.1

### Steps to Reproduce

1. Setup Test Plan
2. Setup Test Case
3. Start a run
4. Attempt to report a bug through a run

### Actual results

A dialog that says to include a base_url

### Expected results

A bug is submitted

**Comment by atodorov** [comment] 2018-09-21 21:01
Did you configure your instance properly https://kiwitcms.readthedocs.io/en/latest/admin.html#configure-kiwi-s-base-url  ?

**Comment by mattouille** [comment] 2018-09-22 21:17
This is the Django Admin section under Sites right? If so, yes.

**Comment by Prome88** [comment] 2018-11-27 08:49
Same issue with JIRA integration. Base URL and all other data is populated the same as in previous versions. Not sure with which version this stopped working but the app returns "Enable reporting to this Issue Tracker by configuring its base_url!"

**Comment by atodorov** [comment] 2019-07-30 11:24
Is this still an issue ? We need to know more about how your GitHub integration is configured b/c this sounds like a misconfiguration. 

Without this information there's nothing else that can be done on our end so I will close this issues after 7 days.

**Comment by atodorov** [comment] 2019-08-12 19:08
Closing due to lack of info and inactivity. If you can still reproduce reopen and provide more information.

**Closed by atodorov** 2019-08-12 19:08 UTC
