### ISSUE TITLE
Testcase.filter() API shows error xml.parsers.expat.ExpatError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by shiron-truong** [kiwitcms/Kiwi#2400] opened 2021-05-26 09:59 UTC
### Description of problem
I use python to search testcases via Kiwitcms API. The TestCase.filter(query) shows error when the search result return a mass of records, it shows error: 
error xml.parsers.expat.ExpatError: not well-formed (invalid token)

### Version or commit hash (if applicable)
10.0

### Additional info (Python traceback, logs, etc.)

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/Users/binhtt/MEGAsync/Works/Sendo/QA/qc-test-infrastructure/kiwi-tcms-import-util/venv/lib/python3.8/site-packages/tcms_api/xmlrpc.py", line 41, in parse_response
    return super().parse_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1336, in parse_response
    p.feed(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 439, in feed
    self._parser.Parse(data, 0)
`

**Comment by atodorov** [comment] 2021-09-06 15:25
What's your script to reproduce ?

**Comment by atodorov** [comment] 2021-09-17 16:10
Closing due to missing information. Feel free to reopen when you can provide the script which reproduces this error.

**Closed by atodorov** 2021-09-17 16:10 UTC
