### ISSUE TITLE
Unable to import attachment with an unexpected character in filename

### ISSUE THREAD

**Issue by nfk** [kiwitcms/Kiwi#2600] opened 2021-11-17 16:39 UTC
### Description of problem

On test run when I filled a comment in a test case I tried to attach a file with a name like this `Screenshot_20211117-164527_Paramètres.png` A popup raised with an error message and the file was not attached.
It works fine when I rename the filename without the `è` charcter.

### Version or commit hash (if applicable)

Kiwi 10.4

### Steps to Reproduce

1. Play a test run
2. Open a test case
3. On the top bar of the text area click on `Insert Image`
4. Attach a file with this name `Screenshot_20211117-164527_Paramètres.png`

### Actual results

A popup raises with this error message ` nternal error: 'ascii' codec can't encode character '\xe8' in position 71: ordinal not in range(128)`

### Expected results

The file is attached successfully.

**Comment by atodorov** [comment] 2021-12-08 15:21
This is a duplicate of https://github.com/kiwitcms/Kiwi/issues/350, which is reported upstream at https://github.com/bartTC/django-attachments/issues/49. 

I managed to reproduce with a file name `Screenshot_2021-12-07 Плащане.png`.

@nfk we're currently running the latest version of django-attachments on Python 3.8 but somehow this bug still appears. Are you able to help reproduce upstream ?

**Comment by nfk** [comment] 2021-12-08 15:40
Hi @atodorov,

I can reproduce this issue on https://public.tenant.kiwitcms.org/runs/3507/ with the a filename like this `écran prioritè.jpg`.

**Comment by atodorov** [comment] 2022-01-14 22:45
This blog post gives the answer https://leimao.github.io/blog/Docker-Locale/ to what the root problem is. 

```
RUN microdnf --nodocs install glibc-langpack-en

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
```

will solve the issue but I need some time to figure out how to design the test for this.

**Closed** 2022-01-15 21:37 UTC
