### ISSUE TITLE
Dockerfile Doesn't Build a Viable Docker Image

### ISSUE THREAD

**Issue by JacobColyer** [kiwitcms/Kiwi#364] opened 2018-06-05 14:31 UTC
### Description of problem
Cloning the repository and creating a Docker Image from the Dockerfile results in a Docker Image that does not run. Several warnings are created about public keys for some packages are not installed

### Component (web, API, etc)
Dockerfile

### Version or commit hash (if applicable)
Latest kiwi code from Github.

### How often reproducible
Always

### Steps to Reproduce

1. Clone the repository (**_git clone https://github.com/kiwitcms/Kiwi.git_**)
2. cd /Kiwi/
3. docker build .
4. Attempt to run the container

### Actual results
Docker fails to create a viable running instance of Kiwi due to some issues with the Dockerfile and files/directories missing.

### Expected results
Docker container is viable, and running the associated commands create a Kiwi instance that is usable.

### Additional info
There seems to be an issue with the RUN /Kiwi/manage.py collectstatic --noinput command. Somehow python isn't being invoked to run the manage.py. I'm assuming that the path has changed for python so it's not automatically called. If I change the Dockerfile RUN command to be RUN python /Kiwi/migrate.py collectstatic --noinput, the image builds successfully.

**Comment by JacobColyer** [comment] 2018-06-06 11:50
Environment: Windows 10 Professional, Docker for Windows.

Follow these commands in this environment and you can observe the issue:

1. Open command prompt or PowerShell.
2. Execute 'git clone https://github.com/kiwitcms/Kiwi.git'
3. Execute 'cd .\Kiwi\'
4. Execute 'docker build -t kiwitcms .'
5. Observe issue at the end of the output

For verbosity, I've attached the command output as a .txt file for your review. 
[result.txt](https://github.com/kiwitcms/Kiwi/files/2075990/result.txt)
From what I can gather, it looks like it's attempting to run the Docker command RUN /Kiwi/manage.py collectstatic --noinput and is looking for 'python' in the /usr/bin/env/ directory.

I don't have much experience with Docker containers apart from going through some online tutorials and reading the documentation.

One workaround I have found is that if I include the actual command 'python' in the command mentioned above, it seems to work fine.

Related output:

Step 20/20 : RUN /Kiwi/manage.py collectstatic --noinput
 ---> Running in b1f4c483773d
/usr/bin/env: python
: No such file or directory
The command '/bin/sh -c /Kiwi/manage.py collectstatic --noinput' returned a non-zero code: 127

**Comment by atodorov** [comment] 2018-06-17 20:32
> From what I can gather, it looks like it's attempting to run the Docker command RUN /Kiwi/manage.py collectstatic --noinput and is looking for 'python' in the /usr/bin/env/ directory.

This is not exactly true.

Docker is trying to execute `/Kiwi/manage.py collectstatic` which is a script file with a `/usr/bin/env` shebang. This means:
1) Start `/usr/bin/env` executable and try to find where the `python` executable is
2) Use the python executable to execute the current script.

I've tried the exact same version of centos/httpd and `/usr/bin/env` is present.

In my attempts `/usr/bin/env python` properly executes Python 3.6.3 from the virtualenv which is created before hand. 


Can you try and reproduce again? Does it happen all the time ? 

If this happens every time for you can you add a `RUN /usr/bin/env` inside the Dockerfile, before the command which fails? This should print the environment inside the container.

I see you are running Docker on Windows, I'm using docker on Linux. Not sure if that has anything to do with this issue though. I don't have experience with Windows.

**Comment by atodorov** [comment] 2018-06-21 21:49
> Dockerfile Doesn't Build a Viable Docker Image

as seen in https://travis-ci.org/kiwitcms/Kiwi/builds/395214134 (PR #378) the `make docker-image` command builds an image successfully. 

I am closing this issue. If you continue to have problems make sure you can reproduce them on CentOS 7 or RHEL 7 linux since this is what we use to build the official images. I can't give advice nor debug platforms I don't have access to.

**Closed by atodorov** 2018-06-21 21:49 UTC
