### ISSUE TITLE
start_date field getting None in TestRun page instead of the actual date and time

### ISSUE THREAD

**Issue by ravitejapagala** [kiwitcms/Kiwi#2394] opened 2021-05-20 18:41 UTC
HINT: try to
Hi 

The issue was closed without fixing Below i mentioned more details
This is the link ----> https://github.com/kiwitcms/Kiwi/issues/2392

### Description of problem
I pulled the latest code from the kiwitcms master branch
Regarding the issue with start_ Date and time field in Testrun page
In the above screenshot of TestRun.filter({"id":2833}) ---->able to see the start_date
But from the 2985(id of the Testrun) it is not showing the start_date value.
I tried it in the https://public.tenant.kiwitcms.org/runs/search/ ------>for all testruns
and https://public.tenant.kiwitcms.org/runs/2999/ ------>testrun
Here I am attaching the screenshots of the jsonrpc and ui of the testrun page

Still observing the same issue where time stamp is not displayed

### Steps to Reproduce

1.login to tcms
2.navigate to Testing ---- NewTestrun
3.Create by giving the necessary details

### Actual results

start_date:None
### Expected results
start_date:current date and time

### Additional info (Python traceback, logs, etc.)
![Screenshot from 2021-05-20 22-13-10](https://user-images.githubusercontent.com/84474944/119031385-a9e6b900-b9c8-11eb-936f-0167a4752b34.png)
![Screenshot from 2021-05-20 22-14-26](https://user-images.githubusercontent.com/84474944/119031394-abb07c80-b9c8-11eb-9a95-9e1744be50a3.png)

**Comment by atodorov** [comment] 2021-05-24 09:07
The displayed value of `None` has been fixed in https://github.com/kiwitcms/Kiwi/pull/2391.

The rest works as intended as already mentioned in #2392.  The shown Test Run doesn't have a value for the `start_date` field hence nothing can be shown on screen.

**Closed by atodorov** 2021-05-24 09:07 UTC
