### ISSUE TITLE
TestRun - Set assignee for multiple test cases - invalid username - user gets error for each selected test case

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#2153] opened 2020-12-15 13:48 UTC
### Description of problem

For X test cases selected user gets error shown X times.

### Version or commit hash (if applicable)
Public v8.9

### Steps to Reproduce

1. Select X test cases on test run page
2. Click on hamburger button 
3. Click on Assignee button
4. Input non-existing user
5. Confirm with OK

### Actual results

Error below shown X times (X being number of test cases)
![image](https://user-images.githubusercontent.com/25688732/102222966-67362780-3ee4-11eb-8643-296f87768c6a.png)

### Expected results

Show error message just once.

**Comment by atodorov** [comment] 2020-12-15 21:19
Closing CANTFIX.

This is working as designed. When performing bulk-update (or any bulk action for that matter) the browser loops over all of the selected items and triggers and API call for the selected action for each of them. That's why they refresh asynchronously.

There is no way to know which of the individual requests has error out or how many of them did because the responses arrive asynchronously. 

It is also not very feasible to check for user existence in this particular case b/c the `User.filter()` API (seeing other user profiles) is guarded by permission which isn't assigned by default and in some cases like on public.tenant will never be.

Workaround: if you see the error twice and know you have selected many rows it may be easier to just refresh the page.

**Closed by atodorov** 2020-12-15 21:19 UTC
