### ISSUE TITLE
Make the component field to a searchable field

### ISSUE THREAD

**Issue by mikii111** [kiwitcms/Kiwi#882] opened 2019-03-28 14:53 UTC
At the moment you need to know all the components name and you need to know the exakt name
 
Would be great if you could have a list with all the components and select the one you need and that the field was searchable 

e.g.
We have a component named 'dynamic attributes'  and one called 'attributes'
I would like to be able to add 'dynamic attributes' without knowing the full name, so if I enter attribute I can select the right one.

**Comment by atodorov** [comment] 2020-01-08 12:49
@mikii111 - on which page is that ? If the issue is still relevant please add more details how to reproduce and screenshots.

**Comment by Prome88** [comment] 2020-01-09 13:19
I'm guessing that he is referring to test case view Components -https://public.tenant.kiwitcms.org/case/5754/ .

![image](https://user-images.githubusercontent.com/25688732/72070803-a8908100-32ea-11ea-806c-59e60171437f.png)

Product has 3 components:

- Test component 1
- Test component 2
- Test component 3

Search is a bit clunky:

- Searching for test gives 0 results
- Searching for Test gives just 2 results
- Searching for compon gives 0 results

I'm assuming that search is case sensitive and only searches from the start.

Drop-down with all available values combined with improved search (non case-sensitive, search over whole string) would be more user friendly.

**Comment by atodorov** [comment] 2020-01-09 13:24
@Prome88 thanks.

"Test component 2" is assigned to a different product, that's why it doesn't come up.

The rest should be easy to do. Just need to instruct the FE layer how to query the DB(, e.g. use name_icontains or similar).

**Comment by Prome88** [comment] 2020-01-09 13:46
I've assigned it to proper Product, but it still only shows 2 results (now Test component 3 is missing)
![image](https://user-images.githubusercontent.com/25688732/72072713-d2e43d80-32ee-11ea-9502-e1f69b9ba38f.png)

**Comment by atodorov** [comment] 2020-01-09 13:54
> I've assigned it to proper Product, but it still only shows 2 results (now Test component 3 is missing)

I can see that the JSON RPC request returns all 3 of them. Maybe the popup widget just displays 2. Appears to be the same behavior wherever the same widget is used. For tags it also shows only 2 entries. For example there are several tags starting with "Adroid " but you need to type the entirety of it (incl. space) to see some of them, otherwise they just don't appear.

**Closed** 2020-10-11 17:16 UTC
