### ISSUE TITLE
Tag and Component Realtime Search results dont display all options

### ISSUE THREAD

**Issue by YouWhy** [kiwitcms/Kiwi#2019] opened 2020-10-15 18:18 UTC
If I search for component or tags, the search results that show up in the shortlist dont give me all options.
For e.g. below, I have already liked Component 4 to a test case and I want to add more components. 
I have typed Component and it shows me Component 1 only. However, I have Component 2 and Component 3 in the database. The tool should show me all 3 options to choose from. 

![image](https://user-images.githubusercontent.com/39198291/96170137-d42f4000-0ee8-11eb-8c4e-f1be54c14567.png)

I think this is a bug

**Comment by atodorov** [comment] 2020-10-15 18:39
Duplicate of https://github.com/kiwitcms/Kiwi/issues/882

**Closed by atodorov** 2020-10-15 18:39 UTC
