### ISSUE TITLE
TC's Summary filed - Special Characters Not show correctly in Tables View

### ISSUE THREAD

**Issue by NirBY** [kiwitcms/Kiwi#2662] opened 2022-01-09 09:52 UTC
### Description of problem
Add Test Case with  special Characters:
```
`:;!@#$%^&*()_-=+[]{}"'?/\,.<>|~€
```
### Version or commit hash (if applicable)
Kiwi Docker V10.5
### Steps to Reproduce
1.Add Test Case with  special Characters
2.Enter Search View 
### Actual results
![image](https://user-images.githubusercontent.com/9214815/148677333-773b7ed5-8f2c-41a7-9a9b-33ba7ce5127e.png)
### Expected results
![image](https://user-images.githubusercontent.com/9214815/148677310-b0654fb9-aefb-4360-bafc-98591b1ec9c9.png)
### Notes
Open issue on TC's Summary, but this is probably happens for other fields in table.

**Comment by atodorov** [comment] 2022-01-10 06:55
Duplicate of https://github.com/kiwitcms/Kiwi/issues/2658

**Closed by atodorov** 2022-01-10 06:55 UTC
