### ISSUE TITLE
Content of test cases is lost after changing status

### ISSUE THREAD

**Issue by QuentinKp** [kiwitcms/Kiwi#1353] opened 2020-02-10 10:55 UTC
### Description of problem

When I change the status of a test case from the test plan view, every field of this test case are erased. I tried to reproduce on your public demo instance but couldn't reproduce.

On my server, I tried to create a new test instance with default settings (I just pulled the git repo and launch docker-compose) and the bug occured. 

### Version or commit hash (if applicable)
latest => v7.3

### Steps to Reproduce

1. Create test case in a test plan with **Proposed** status
2. From the test plan view, change the status of this test case to **Confirmed**

### Actual results

The status is changed but every data in the test case are erased

### Expected results

The status is changed and every data in the test case are still here

**Comment by atodorov** [comment] 2020-02-10 11:41
Duplicate of #1318

The fix will be released in the next version.

**Closed by atodorov** 2020-02-10 11:41 UTC
