### ISSUE TITLE
Header - Test Run / Test plan - Header height is too big

### ISSUE THREAD

**Issue by Prome88** [kiwitcms/Kiwi#706] opened 2019-01-11 08:32 UTC
### Description of problem
Header height on view:
- Test plan
- Test run

is too high and it takes too much space on the site as another iframe is inserted.

### Version or commit hash (if applicable)
6.4 and previous versions

### Steps to Reproduce

Open:
- Test plan
- Test run

### Actual results

![image](https://user-images.githubusercontent.com/25688732/51022130-b8647080-1583-11e9-8a5b-1e6b6222359c.png)

### Expected results
Same height as on Dashboard:
![image](https://user-images.githubusercontent.com/25688732/51022031-6d4a5d80-1583-11e9-8636-99485bcb1f11.png)

### Additional info (Python traceback, logs, etc.)
```
<iframe src="/navigation/" scrolling="no" width="100%" height="195px" frameborder="0"></iframe>
```

**Comment by atodorov** [comment] 2019-01-11 10:39
This is by design until we can convert all of the existing pages to the new design. Redesigning them one by one is an ongoing effort.

There reason for the iframe is conflicting JavaScript (jQuery) libraries. Nothing we can do for that by itself so closing.

**Closed by atodorov** 2019-01-11 10:39 UTC
