### ISSUE TITLE
Add new test case page display abnormal

### ISSUE THREAD

**Issue by dawzhang** [kiwitcms/Kiwi#665] opened 2018-12-18 03:59 UTC
**Open new test case page and display abnormal .** 

![default](https://user-images.githubusercontent.com/5270671/50131050-56358a00-02bb-11e9-8aca-1d2c473b7e2a.png)

**Kiwi TCMS Version : 6.3**

![default](https://user-images.githubusercontent.com/5270671/50131077-7107fe80-02bb-11e9-94f3-1b175a7069bc.png)

**Browse Version : firefox 64 ; chrome 71.0.3578.98**

![default](https://user-images.githubusercontent.com/5270671/50131133-b5939a00-02bb-11e9-9816-be79c1a29dc0.png)
![default](https://user-images.githubusercontent.com/5270671/50131138-ba584e00-02bb-11e9-9d11-8f98d8173761.png)

**Browse Console Log**

![default](https://user-images.githubusercontent.com/5270671/50131260-51bda100-02bc-11e9-8d08-2fb722be7cf1.png)

**Windows DPI：**
![default](https://user-images.githubusercontent.com/5270671/50131217-17540400-02bc-11e9-9b9b-9b232caeeba8.png)

**Comment by atodorov** [comment] 2018-12-18 09:07
Yes, duplicate of #315

**Closed by atodorov** 2018-12-18 09:07 UTC
