### ISSUE TITLE
Duplicate functional menu item on Top Menu

### ISSUE THREAD

**Issue by shiron-truong** [kiwitcms/Kiwi#2202] opened 2021-01-18 03:56 UTC
### Description of problem
![image](https://user-images.githubusercontent.com/50346670/104870573-70029900-597b-11eb-8a36-7e24bc33fdd7.png)

![image](https://user-images.githubusercontent.com/50346670/104870829-08991900-597c-11eb-9154-891b9ed23186.png)

![image](https://user-images.githubusercontent.com/50346670/104870851-1babe900-597c-11eb-83c9-78965a915308.png)

### Version or commit hash (if applicable)
Version 9.0

It looks that my clients doesn't clear cache after I upgraded to v9.0. But I have no idea what's happened. :( 
### Additional info (Python traceback, logs, etc.)
Occur all al browsers (Safari, Chrome,...)
I stop the docker and restart then it will back to normal.

**Comment by atodorov** [comment] 2021-01-18 13:35
Duplicate of #991 .

This happens inconsistently when something crashes while the user is on an edit page (I think). You may want to check your logs for other telltale signs that your users are having troubles.

Restarting the containers fixes the issue.

**Closed by atodorov** 2021-01-18 13:35 UTC
