### ISSUE TITLE
Settings items repeating in menu

### ISSUE THREAD

**Issue by KartikEK** [kiwitcms/Kiwi#2348] opened 2021-04-20 05:27 UTC
if group of people using this site, everyone is getting the setting menu of opened object in their window.  Refer the screenshot,
![image](https://user-images.githubusercontent.com/20593145/115341955-18b4d480-a1c7-11eb-8ed2-27e44156ef73.png)

I feel, this needs to corrected, it only shows the respective users object setting. But not others.

**Comment by atodorov** [comment] 2021-04-22 13:02
Duplicate of #991 and fixed in v10.0

**Closed by atodorov** 2021-04-22 13:02 UTC
