### ISSUE TITLE
Add option to attach a file to a Test Run

### ISSUE THREAD

**Issue by ronfeldman** [kiwitcms/Kiwi#1702] opened 2020-05-26 16:41 UTC
**Problem**
When I execute tests in another tool, such as ReadyAPI, it generates a report that I want to associate with a Test Run

**Solution**
Add option to attach a file to a Test Run

**Additional info**
Files can be attached to Test Executions, but this is too granular when the report is for a Test Suite.

**Current workaround**
Need to generate reports in ReadyAPI for each Test Case execution and attach individual reports to Test Executions. This maintains traceability but is not really useful to view on a regular basis.

**Comment by atodorov** [comment] 2020-05-26 19:14
Duplicate of https://github.com/kiwitcms/Kiwi/issues/872

**Closed by atodorov** 2020-05-26 19:14 UTC
