### ISSUE TITLE
Settings button gets duplicated when Test Run is Cloned

### ISSUE THREAD

**Issue by Civiani** [kiwitcms/Kiwi#2219] opened 2021-01-25 13:07 UTC
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
Settings button gets duplicated when Test Run is Cloned and when the Test Run is tried to be opened sometimes 500 Internal Server Error is shown instead of showing the Test Run.

### Version or commit hash (if applicable)
Kiwi TCMS 8.9 (07 Dec 2020)

### Steps to Reproduce

1. Create new test plan
2. Create new test cases 
3. Assign the created test cases from point 2 to the created test plan from point 1.
4. Confirm all the created test cases.
5. Run the test plan created from point 1.
6. Clone the Test Run 
7. Test Run is cloned BUT not with the state of the the original cloned test cases (all of them are IDLE)
8. Settings button on the TOP panel is Duplicated (should not be the case - obviously its a bug)
9. If I go back to the DASHBOARD and click and open the Cloned Test Run, sometimes it opens it sometimes it gives the Error 500 Internal Server Error.

### Actual results
Settings button duplicates and sometimes 500 Internal Server Error is shown when the Test Run is tried to be opened.

### Expected results
Settings button shouldn't be duplicated and 500 Internal Server Error shouldn't be shown.

**Comment by atodorov** [comment] 2021-01-25 13:14
Duplicate of #991

**Closed by atodorov** 2021-01-25 13:14 UTC
