### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by sniperyi09** [kiwitcms/Kiwi#2519] opened 2021-09-08 09:11 UTC
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Steps to Reproduce

1.
2.
3.

**Comment by atodorov** [comment] 2021-09-08 09:32
@sniperyi09 which page triggers the problem for you? What are your steps to reproduce ?

**Comment by atodorov** [comment] 2021-09-17 16:09
Closing due to missing information. Feel free to reopen when you can provide more details.

**Closed by atodorov** 2021-09-17 16:09 UTC
