### ISSUE TITLE
Feature: Adding Custom Fields for Test Plan and Test Case

### ISSUE THREAD

**Issue by edoswaldgo** [kiwitcms/Kiwi#1368] opened 2020-02-12 12:31 UTC
Good day,

I would like to request for the feature of adding custom fields to test plans and cases for advanced filtering. May I know if this feature is viable to be added to Kiwi TCMS?

Thank you very much!

**Comment by atodorov** [comment] 2020-02-12 12:41
Essentially duplicate of #156

**Closed by atodorov** 2020-02-12 12:41 UTC

**Comment by edoswaldgo** [comment] 2020-02-12 12:43
Thanks for the clarification, @atodorov !
